language: ruby
rvm:
 - 2.1.0
 - 2.0.0
 - 1.9.3
 - 1.9.2
 - jruby-19mode
 - rbx-2.1.1
jdk:
 - openjdk6
 - openjdk7
 - oraclejdk7
matrix:
  exclude:
    - rvm: rbx-2.1.1
      jdk: openjdk6
    - rvm: rbx-2.1.1
      jdk: openjdk7
    - rvm: rbx-2.1.1
      jdk: oraclejdk7

    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: oraclejdk7

    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7

    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7

    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7

    - rvm: jruby-19mode
      jdk: openjdk6
    - rvm: jruby-19mode
      jdk: openjdk7
    - rvm: jruby-19mode
      jdk: oraclejdk7

  include:
    - rvm: 2.1.0
      jdk:

    - rvm: 2.0.0
      jdk:

    - rvm: 1.9.3
      jdk:

    - rvm: 1.9.2
      jdk:

    - rvm: rbx-2.1.1
      jdk:

    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcext.enabled=true"
      jdk: openjdk6

    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcext.enabled=true"
      jdk: openjdk7

    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcext.enabled=true"
      jdk: oraclejdk7

gemfile:
 - Gemfile
branches:
  only:
    - devel
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libicu-dev
 - bundle install
