language: ruby
rvm:
 - 1.9.3
 - jruby-19mode
 - rbx-19mode
jdk:
 - openjdk6
gemfile:
 - Gemfile
branches:
  only:
    - devel 
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libicu-dev
