language: ruby
rvm:
 - 2.1.0
 - 2.0.0
 - 1.9.3
 - 1.9.2
 - jruby-19mode
 - rbx-2.1.1
jdk:
 - openjdk6
 - openjdk7
 - oraclejdk7
matrix:
  include:
    - rvm: 2.1.0
    - rvm: 2.0.0
    - rvm: 1.9.3
    - rvm: 1.9.2
    - rvm: rbx-2.1.1

    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcext.enabled=true"
      jdk: openjdk6

    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcext.enabled=true"
      jdk: openjdk7

    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcext.enabled=true"
      jdk: oraclejdk7

gemfile:
 - Gemfile
branches:
  only:
    - devel
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libicu-dev
